In [1]:
import numpy as np

In [2]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
list(range(.4,6))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
list(np.arange(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
list(np.arange(0.2,11,0.2))

[0.2,
 0.4,
 0.6000000000000001,
 0.8,
 1.0,
 1.2,
 1.4000000000000001,
 1.6,
 1.8,
 2.0,
 2.2,
 2.4000000000000004,
 2.6000000000000005,
 2.8000000000000003,
 3.0000000000000004,
 3.2,
 3.4000000000000004,
 3.6000000000000005,
 3.8000000000000003,
 4.0,
 4.2,
 4.4,
 4.6000000000000005,
 4.800000000000001,
 5.000000000000001,
 5.2,
 5.4,
 5.6000000000000005,
 5.800000000000001,
 6.000000000000001,
 6.2,
 6.4,
 6.6000000000000005,
 6.800000000000001,
 7.000000000000001,
 7.2,
 7.4,
 7.6000000000000005,
 7.800000000000001,
 8.0,
 8.2,
 8.4,
 8.6,
 8.799999999999999,
 9.0,
 9.2,
 9.4,
 9.6,
 9.8,
 10.0,
 10.2,
 10.4,
 10.6,
 10.8]

In [11]:
np.arange(0.2,11,0.2)

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
        2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
        4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
        6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
        9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8])

In [8]:
# the above function is for iterating the floating point values by using a numpy "arange" function

In [10]:
np.linspace(2,22)

array([ 2.        ,  2.40816327,  2.81632653,  3.2244898 ,  3.63265306,
        4.04081633,  4.44897959,  4.85714286,  5.26530612,  5.67346939,
        6.08163265,  6.48979592,  6.89795918,  7.30612245,  7.71428571,
        8.12244898,  8.53061224,  8.93877551,  9.34693878,  9.75510204,
       10.16326531, 10.57142857, 10.97959184, 11.3877551 , 11.79591837,
       12.20408163, 12.6122449 , 13.02040816, 13.42857143, 13.83673469,
       14.24489796, 14.65306122, 15.06122449, 15.46938776, 15.87755102,
       16.28571429, 16.69387755, 17.10204082, 17.51020408, 17.91836735,
       18.32653061, 18.73469388, 19.14285714, 19.55102041, 19.95918367,
       20.36734694, 20.7755102 , 21.18367347, 21.59183673, 22.        ])

In [12]:
np.linspace(2,22,200)

array([ 2.        ,  2.10050251,  2.20100503,  2.30150754,  2.40201005,
        2.50251256,  2.60301508,  2.70351759,  2.8040201 ,  2.90452261,
        3.00502513,  3.10552764,  3.20603015,  3.30653266,  3.40703518,
        3.50753769,  3.6080402 ,  3.70854271,  3.80904523,  3.90954774,
        4.01005025,  4.11055276,  4.21105528,  4.31155779,  4.4120603 ,
        4.51256281,  4.61306533,  4.71356784,  4.81407035,  4.91457286,
        5.01507538,  5.11557789,  5.2160804 ,  5.31658291,  5.41708543,
        5.51758794,  5.61809045,  5.71859296,  5.81909548,  5.91959799,
        6.0201005 ,  6.12060302,  6.22110553,  6.32160804,  6.42211055,
        6.52261307,  6.62311558,  6.72361809,  6.8241206 ,  6.92462312,
        7.02512563,  7.12562814,  7.22613065,  7.32663317,  7.42713568,
        7.52763819,  7.6281407 ,  7.72864322,  7.82914573,  7.92964824,
        8.03015075,  8.13065327,  8.23115578,  8.33165829,  8.4321608 ,
        8.53266332,  8.63316583,  8.73366834,  8.83417085,  8.93

In [14]:
np.logspace(1,4,10 ,base=2)

array([ 2.        ,  2.5198421 ,  3.1748021 ,  4.        ,  5.0396842 ,
        6.34960421,  8.        , 10.0793684 , 12.69920842, 16.        ])

In [15]:
np.logspace(1,4,10 ,base=10)

array([   10.        ,    21.5443469 ,    46.41588834,   100.        ,
         215.443469  ,   464.15888336,  1000.        ,  2154.43469003,
        4641.58883361, 10000.        ])

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr=np.ones((5,3))

In [23]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr+5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [26]:
np.zeros((4,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.zeros((3,4,6,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0

In [28]:
np.ones((2,3,4,5,6))

array([[[[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1

In [31]:
np.empty((4,5))

array([[7.56592338e-307, 9.34588061e-307, 4.45014772e-307,
        1.61324391e-307, 1.60219035e-306],
       [1.37961302e-306, 2.41911114e-312, 1.61324645e-307,
        4.67296746e-307, 1.69121096e-306],
       [7.56595733e-307, 1.89146896e-307, 7.56571288e-307,
        3.11525958e-307, 1.24610723e-306],
       [1.29061142e-306, 4.22792892e-307, 3.44897992e-307,
        3.33773471e-307, 1.89143501e-307]])

In [32]:
np.empty((3,4))

array([[1.01855798e-312, 1.10343781e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.16709769e-312, 1.03977794e-312, 1.23075756e-312,
        1.03977794e-312],
       [1.03977794e-312, 9.76118064e-313, 1.10343781e-312,
        1.90979621e-312]])

In [34]:
arr=np.eye(6)

In [35]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
import pandas as pd

In [37]:
pd.DataFrame(arr)

0    1    2    3    4    5
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0

In [38]:
pd.DataFrame(np.eye(6))

0    1    2    3    4    5
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0

In [39]:
np.random.rand(2,3)

array([[0.69692092, 0.64850607, 0.12193937],
       [0.76739593, 0.38506316, 0.16845241]])

In [40]:
np.random.randn(2,3)

array([[-1.10446086,  0.44970592, -0.57768389],
       [-0.53994698,  0.27485845, -2.15245332]])

In [41]:
np.random.randint(2,3)

2

In [42]:
np.random.randint(2,10)

6

In [46]:
arr2=np.random.randint(2,10,(5,5))

In [47]:
arr2

array([[2, 3, 7, 9, 3],
       [3, 3, 9, 6, 5],
       [2, 6, 7, 5, 3],
       [8, 8, 4, 3, 4],
       [6, 9, 9, 7, 5]])

In [48]:
arr2

array([[2, 3, 7, 9, 3],
       [3, 3, 9, 6, 5],
       [2, 6, 7, 5, 3],
       [8, 8, 4, 3, 4],
       [6, 9, 9, 7, 5]])

In [49]:
arr2.shape

(5, 5)

In [50]:
arr2.size

25

In [52]:
arr3=np.random.randint(1,5,(4,3))

In [53]:
arr3

array([[4, 2, 1],
       [3, 1, 4],
       [4, 4, 3],
       [4, 4, 1]])

In [54]:
arr3.reshape(6,2)

array([[4, 2],
       [1, 3],
       [1, 4],
       [4, 4],
       [3, 4],
       [4, 1]])

In [55]:
arr3.reshape(3,4)

array([[4, 2, 1, 3],
       [1, 4, 4, 4],
       [3, 4, 4, 1]])

In [56]:
arr3.reshape(4,-1)

array([[4, 2, 1],
       [3, 1, 4],
       [4, 4, 3],
       [4, 4, 1]])

In [57]:
arr3.reshape(4,-137846726)

array([[4, 2, 1],
       [3, 1, 4],
       [4, 4, 3],
       [4, 4, 1]])

In [59]:
arr4=np.random.randint(1,11,(5,6))

In [60]:
arr4

array([[ 4,  8, 10,  7,  5,  3],
       [ 5, 10,  7,  8,  3,  5],
       [ 8,  7,  1,  8, 10, 10],
       [ 6,  2,  5,  7,  7,  7],
       [ 3,  4,  4,  7,  9,  1]])

In [61]:
arr4>3

array([[ True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True, False,  True],
       [ True,  True, False,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False]])

In [62]:
arr4>8

array([[False, False,  True, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [64]:
arr4[arr4>8]

array([10, 10, 10, 10,  9])

In [65]:
arr4[arr4>3]

array([ 4,  8, 10,  7,  5,  5, 10,  7,  8,  5,  8,  7,  8, 10, 10,  6,  5,
        7,  7,  7,  4,  4,  7,  9])

In [70]:
arr1=np.random.randint(1,6,(5,6))

In [71]:
arr1

array([[5, 4, 1, 1, 4, 4],
       [5, 3, 2, 2, 2, 5],
       [2, 3, 4, 4, 5, 3],
       [4, 3, 5, 3, 5, 1],
       [4, 5, 5, 3, 3, 4]])

In [72]:
arr1[0]

array([5, 4, 1, 1, 4, 4])

In [73]:
arr1[0,[0,1]]

array([5, 4])

In [75]:
arr1[2:5,[2,3,4]]

array([[4, 4, 5],
       [5, 3, 5],
       [5, 3, 3]])

In [77]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [79]:
arr1

array([[2, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [80]:
arr2

array([[2, 1, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [81]:
arr1+arr2

array([[4, 2, 3],
       [3, 3, 3],
       [2, 3, 3]])

In [82]:
arr1-arr2

array([[ 0,  0,  1],
       [-1,  1, -1],
       [ 0, -1,  1]])

In [83]:
arr1*arr2

array([[4, 1, 2],
       [2, 2, 2],
       [1, 2, 2]])

In [84]:
arr1/arr2

array([[1. , 1. , 2. ],
       [0.5, 2. , 0.5],
       [1. , 0.5, 2. ]])

In [86]:
arr1@arr2

array([[8, 7, 6],
       [7, 5, 6],
       [6, 6, 5]])

In [87]:
arr2

array([[2, 1, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [88]:
arr1

array([[2, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [89]:
arr1/0

C:\Users\chand\AppData\Local\Temp\ipykernel_13424\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [90]:
#numpy - broadcasting

In [91]:
arr1

array([[2, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [92]:
arr1=np.random.randint(1,5,(5,6))

In [93]:
arr1

array([[3, 1, 1, 2, 1, 1],
       [4, 3, 2, 2, 1, 2],
       [4, 1, 4, 3, 1, 3],
       [4, 3, 4, 2, 1, 1],
       [3, 1, 4, 1, 3, 4]])

In [97]:
arr=np.zeros((5,5))

In [98]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
a=np.array([1,2,4,5,6])

In [100]:
arr+a

array([[1., 2., 4., 5., 6.],
       [1., 2., 4., 5., 6.],
       [1., 2., 4., 5., 6.],
       [1., 2., 4., 5., 6.],
       [1., 2., 4., 5., 6.]])

In [104]:
b=np.array([3,45,5,3,5])

In [105]:
arr+b.T

array([[ 3., 45.,  5.,  3.,  5.],
       [ 3., 45.,  5.,  3.,  5.],
       [ 3., 45.,  5.,  3.,  5.],
       [ 3., 45.,  5.,  3.,  5.],
       [ 3., 45.,  5.,  3.,  5.]])

In [112]:
arr5=np.random.randint(1,7,(4,4))

In [113]:
arr5

array([[2, 3, 3, 3],
       [4, 2, 4, 2],
       [2, 2, 4, 5],
       [6, 1, 4, 2]])

In [114]:
arr5=np.random.randint(1.6,7.8,(4,4))

In [115]:
arr5

array([[2, 2, 4, 5],
       [3, 4, 2, 3],
       [4, 1, 5, 2],
       [5, 5, 5, 2]])

In [116]:
np.array(arr5)

array([[2, 2, 4, 5],
       [3, 4, 2, 3],
       [4, 1, 5, 2],
       [5, 5, 5, 2]])

In [117]:
np.min(arr5)

1

In [118]:
np.max(arr5)

5

In [119]:
np.exp(arr5)

array([[  7.3890561 ,   7.3890561 ,  54.59815003, 148.4131591 ],
       [ 20.08553692,  54.59815003,   7.3890561 ,  20.08553692],
       [ 54.59815003,   2.71828183, 148.4131591 ,   7.3890561 ],
       [148.4131591 , 148.4131591 , 148.4131591 ,   7.3890561 ]])

In [120]:
np.sqrt(arr5)

array([[1.41421356, 1.41421356, 2.        , 2.23606798],
       [1.73205081, 2.        , 1.41421356, 1.73205081],
       [2.        , 1.        , 2.23606798, 1.41421356],
       [2.23606798, 2.23606798, 2.23606798, 1.41421356]])

In [121]:
np.log10(arr5)

array([[0.30103   , 0.30103   , 0.60205999, 0.69897   ],
       [0.47712125, 0.60205999, 0.30103   , 0.47712125],
       [0.60205999, 0.        , 0.69897   , 0.30103   ],
       [0.69897   , 0.69897   , 0.69897   , 0.30103   ]])

In [122]:
np.log2(arr5)

array([[1.        , 1.        , 2.        , 2.32192809],
       [1.5849625 , 2.        , 1.        , 1.5849625 ],
       [2.        , 0.        , 2.32192809, 1.        ],
       [2.32192809, 2.32192809, 2.32192809, 1.        ]])