In [1]:
import numpy as np

In [3]:
arr=np.array([2,5,2,4,43,24,67,32,453,34])

In [4]:
arr

array([  2,   5,   2,   4,  43,  24,  67,  32, 453,  34])

In [5]:
np.sort(arr)

array([  2,   2,   4,   5,  24,  32,  34,  43,  67, 453])

In [6]:
np.searchsorted(arr,35)

8

In [7]:
np.searchsorted(arr,6)

4

In [9]:
arr1=np.array([0,324,645,65,6,6,0,0,0,234])

In [10]:
np.count_nonzero(arr1)

6

In [11]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [13]:
np.extract(arr1>0,arr1)

array([324, 645,  65,   6,   6, 234])

In [14]:
#copies and views

In [15]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [17]:
arr1.view()

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [18]:
a=np.copy(arr1)

In [19]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [21]:
b=arr1.view()

In [22]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [23]:
b=arr1

In [24]:
b[0]=234

In [25]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [26]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [27]:
arr1.view()

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [29]:
#numpy - matrix library

In [30]:
import numpy.matlib as nm


In [31]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [32]:
nm.ones((4,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [48]:
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[3,5],[4,5]])

In [49]:
arr1

array([[1, 2],
       [1, 1]])

In [50]:
arr2

array([[2, 4],
       [3, 4]])

In [51]:
arr1@arr2

array([[ 8, 12],
       [ 5,  8]])

In [52]:
np.dot(arr1,arr2)

array([[ 8, 12],
       [ 5,  8]])