In [1]:
import numpy as np

In [2]:
#array - manipulation

In [5]:
arr=np.random.randint(1,10,(4,4))

In [6]:
arr

array([[8, 8, 8, 8],
       [9, 2, 8, 4],
       [7, 4, 4, 3],
       [1, 5, 8, 6]])

In [7]:
arr.reshape(8,2)

array([[8, 8],
       [8, 8],
       [9, 2],
       [8, 4],
       [7, 4],
       [4, 3],
       [1, 5],
       [8, 6]])

In [8]:
arr.reshape(2,8)

array([[8, 8, 8, 8, 9, 2, 8, 4],
       [7, 4, 4, 3, 1, 5, 8, 6]])

In [9]:
arr.flatten()

array([8, 8, 8, 8, 9, 2, 8, 4, 7, 4, 4, 3, 1, 5, 8, 6])

In [11]:
arr

array([[8, 8, 8, 8],
       [9, 2, 8, 4],
       [7, 4, 4, 3],
       [1, 5, 8, 6]])

In [12]:
np.expand_dims(arr,axis=1)

array([[[8, 8, 8, 8]],

       [[9, 2, 8, 4]],

       [[7, 4, 4, 3]],

       [[1, 5, 8, 6]]])

In [13]:
np.expand_dims(arr,axis=0)

array([[[8, 8, 8, 8],
        [9, 2, 8, 4],
        [7, 4, 4, 3],
        [1, 5, 8, 6]]])

In [15]:
data=np.array([[1],[2],[3]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
data.squeeze()

array([1, 2, 3])

In [18]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [19]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [20]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [21]:
data

array([[1],
       [2],
       [3]])

In [22]:
np.roll(data,4)

array([[3],
       [1],
       [2]])

In [23]:
np.roll(data,7)

array([[3],
       [1],
       [2]])

In [25]:
arr1=np.array([1,2,3,4,5])

In [29]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [30]:
name=np.array(['subhash','chandra','bose','bhagath','singh'])

In [31]:
np.diag(name)

array([['subhash', '', '', '', ''],
       ['', 'chandra', '', '', ''],
       ['', '', 'bose', '', ''],
       ['', '', '', 'bhagath', ''],
       ['', '', '', '', 'singh']], dtype='<U7')

In [32]:
#numpy-binary operator

In [33]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [34]:
arr1+arr2

array([[ 9, 12, 15],
       [ 7, 16, 13],
       [10,  7, 13]])

In [35]:
arr1-arr2

array([[ 7,  6,  3],
       [-5, -2, -1],
       [-2,  1,  5]])

In [36]:
arr1*arr2

array([[ 8, 27, 54],
       [ 6, 63, 42],
       [24, 12, 36]])

In [37]:
arr1/arr2

array([[8.        , 3.        , 1.5       ],
       [0.16666667, 0.77777778, 0.85714286],
       [0.66666667, 1.33333333, 2.25      ]])

In [38]:
arr1**arr2

array([[       8,      729,   531441],
       [       1, 40353607,   279936],
       [    4096,       64,     6561]])

In [39]:
~arr1

array([[ -9, -10, -10],
       [ -2,  -8,  -7],
       [ -5,  -5, -10]])

In [40]:
arr1

array([[8, 9, 9],
       [1, 7, 6],
       [4, 4, 9]])

In [41]:
arr1>arr2

array([[ True,  True,  True],
       [False, False, False],
       [False,  True,  True]])

In [42]:
arr1

array([[8, 9, 9],
       [1, 7, 6],
       [4, 4, 9]])

In [43]:
arr2

array([[1, 3, 6],
       [6, 9, 7],
       [6, 3, 4]])

In [44]:
arr1>arr2

array([[ True,  True,  True],
       [False, False, False],
       [False,  True,  True]])

In [45]:
np.fromstring("Virat Kohli is an Indian international cricketer and the former captain of the Indian national cricket team. He is a right-handed batsman and an occasional medium-fast bowler. He currently represents Royal Challengers Bengaluru in the IPL and Delhi in domestic cricket",sep=" ")

C:\Users\chand\AppData\Local\Temp\ipykernel_10784\1654457902.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("Virat Kohli is an Indian international cricketer and the former captain of the Indian national cricket team. He is a right-handed batsman and an occasional medium-fast bowler. He currently represents Royal Challengers Bengaluru in the IPL and Delhi in domestic cricket.",sep=" ")


array([], dtype=float64)

In [46]:
text = "Virat Kohli is an Indian international cricketer and the former captain of the Indian national cricket team. He is a right-handed batsman and an occasional medium-fast bowler. He currently represents Royal Challengers Bengaluru in the IPL and Delhi in domestic cricket"
words_array = text.split(" ")  # This will split the string into a list of words based on spaces

# Now 'words_array' is a Python list containing each word as an element.


In [47]:
import numpy as np

words_np_array = np.array(words_array)


In [48]:
words_np_array

array(['Virat', 'Kohli', 'is', 'an', 'Indian', 'international',
       'cricketer', 'and', 'the', 'former', 'captain', 'of', 'the',
       'Indian', 'national', 'cricket', 'team.', 'He', 'is', 'a',
       'right-handed', 'batsman', 'and', 'an', 'occasional',
       'medium-fast', 'bowler.', 'He', 'currently', 'represents', 'Royal',
       'Challengers', 'Bengaluru', 'in', 'the', 'IPL', 'and', 'Delhi',
       'in', 'domestic', 'cricket'], dtype='<U13')

In [52]:
arr=np.array(['virat','kohli'])

In [53]:
arr

array(['virat', 'kohli'], dtype='<U5')

In [54]:
np.char.upper(arr)

array(['VIRAT', 'KOHLI'], dtype='<U5')

In [55]:
np.char.capitalize(arr)

array(['Virat', 'Kohli'], dtype='<U5')

In [59]:
np.char.title(arr)

array(['Virat', 'Kohli'], dtype='<U5')

In [60]:
#numpy-mathematical functions

In [61]:
arr

array(['virat', 'kohli'], dtype='<U5')

In [62]:
arr1

array([[8, 9, 9],
       [1, 7, 6],
       [4, 4, 9]])

In [63]:
np.sin(arr1)

array([[ 0.98935825,  0.41211849,  0.41211849],
       [ 0.84147098,  0.6569866 , -0.2794155 ],
       [-0.7568025 , -0.7568025 ,  0.41211849]])

In [64]:
np.cos(arr1)

array([[-0.14550003, -0.91113026, -0.91113026],
       [ 0.54030231,  0.75390225,  0.96017029],
       [-0.65364362, -0.65364362, -0.91113026]])

In [65]:
np.tan(arr1)

array([[-6.79971146, -0.45231566, -0.45231566],
       [ 1.55740772,  0.87144798, -0.29100619],
       [ 1.15782128,  1.15782128, -0.45231566]])

In [69]:
np.log(arr1)

array([[2.07944154, 2.19722458, 2.19722458],
       [0.        , 1.94591015, 1.79175947],
       [1.38629436, 1.38629436, 2.19722458]])

In [70]:
np.log10(arr1)

array([[0.90308999, 0.95424251, 0.95424251],
       [0.        , 0.84509804, 0.77815125],
       [0.60205999, 0.60205999, 0.95424251]])

In [71]:
np.exp(arr1)

array([[2.98095799e+03, 8.10308393e+03, 8.10308393e+03],
       [2.71828183e+00, 1.09663316e+03, 4.03428793e+02],
       [5.45981500e+01, 5.45981500e+01, 8.10308393e+03]])

In [74]:
np.power(arr1,arr2)

array([[       8,      729,   531441],
       [       1, 40353607,   279936],
       [    4096,       64,     6561]])

In [75]:
np.power(arr2,arr1)

array([[       1,    19683, 10077696],
       [       6,  4782969,   117649],
       [    1296,       81,   262144]])

In [76]:
np.mean(arr1)

6.333333333333333

In [77]:
np.median(arr1)

7.0

In [78]:
np.std(arr1)

2.6666666666666665

In [79]:
np.var(arr1)

7.111111111111111

In [80]:
np.min(arr1)

1

In [81]:
np.max(arr1)

9

In [82]:
#numpy-arithmatic operations

In [83]:
arr1

array([[8, 9, 9],
       [1, 7, 6],
       [4, 4, 9]])

In [84]:
arr2

array([[1, 3, 6],
       [6, 9, 7],
       [6, 3, 4]])

In [85]:
arr1+arr2

array([[ 9, 12, 15],
       [ 7, 16, 13],
       [10,  7, 13]])

In [86]:
arr1-arr2

array([[ 7,  6,  3],
       [-5, -2, -1],
       [-2,  1,  5]])

In [87]:
arr1*arr2

array([[ 8, 27, 54],
       [ 6, 63, 42],
       [24, 12, 36]])

In [88]:
np.mod(arr1,arr2)

array([[0, 0, 3],
       [1, 7, 6],
       [4, 1, 1]])

In [89]:
np.subtract(arr1,arr2)

array([[ 7,  6,  3],
       [-5, -2, -1],
       [-2,  1,  5]])

In [90]:
np.multiply(arr1,arr2)

array([[ 8, 27, 54],
       [ 6, 63, 42],
       [24, 12, 36]])

In [91]:
np.mod(arr1,arr2)

array([[0, 0, 3],
       [1, 7, 6],
       [4, 1, 1]])

In [93]:
np.power(arr1,arr2)

array([[       8,      729,   531441],
       [       1, 40353607,   279936],
       [    4096,       64,     6561]])

In [95]:
np.sqrt(arr1)

array([[2.82842712, 3.        , 3.        ],
       [1.        , 2.64575131, 2.44948974],
       [2.        , 2.        , 3.        ]])

In [96]:
np.sqrt(arr2)

array([[1.        , 1.73205081, 2.44948974],
       [2.44948974, 3.        , 2.64575131],
       [2.44948974, 1.73205081, 2.        ]])

In [97]:
#numpy- statistical functions

In [98]:
np.mean(arr1)

6.333333333333333

In [99]:
np.median(arr2)

6.0

In [100]:
np.std(arr1)

2.6666666666666665