In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [4]:
arr=np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [8]:
arr1=[[1,2,3],[2,3,4]]

In [9]:
arr1

[[1, 2, 3], [2, 3, 4]]

In [10]:
arr.ndim

1

In [11]:
type(arr1)

list

In [16]:
arr1=np.array([[1,2,3],[2,3,4]])

In [17]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
type(arr1)

numpy.ndarray

In [19]:
arr1.ndim

2

In [20]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
arr

array([1, 2, 3, 4, 5, 6])

In [22]:
l

[1, 2, 3, 4, 5, 6]

In [23]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5, 6]])

In [24]:
np.matrix(arr1)

matrix([[1, 2, 3],
        [2, 3, 4]])

In [25]:
np.matrix(arr)

matrix([[1, 2, 3, 4, 5, 6]])

In [26]:
mat=np.matrix(l)

In [27]:
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [28]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [29]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6]])

In [30]:
mat1=np.matrix(l)

In [31]:
mat1

matrix([[1, 2, 3, 4, 5, 6]])

In [32]:
np.asanyarray(mat1)

matrix([[1, 2, 3, 4, 5, 6]])

In [33]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [34]:
np.asanyarray(arr)

array([1, 2, 3, 4, 5, 6])

In [35]:
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
a=arr

In [37]:
a

array([1, 2, 3, 4, 5, 6])

In [38]:
arr

array([1, 2, 3, 4, 5, 6])

In [39]:
a[0]=100

In [40]:
arr

array([100,   2,   3,   4,   5,   6])

In [41]:
a

array([100,   2,   3,   4,   5,   6])

In [52]:
#shallow copying

In [42]:
a=np.copy(arr)

In [43]:
a

array([100,   2,   3,   4,   5,   6])

In [44]:
arr

array([100,   2,   3,   4,   5,   6])

In [45]:
a[0]=343

In [46]:
arr

array([100,   2,   3,   4,   5,   6])

In [47]:
a

array([343,   2,   3,   4,   5,   6])

In [48]:
arr[0]=233

In [49]:
arr

array([233,   2,   3,   4,   5,   6])

In [50]:
a

array([343,   2,   3,   4,   5,   6])

In [54]:
np.fromfunction(lambda i,j: i==j, (4,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [55]:
np.fromfunction(lambda i,j: i==j, (5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [56]:
np.fromfunction(lambda i,j: i>j, (4,5))

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False]])

In [57]:
np.fromfunction(lambda i,j: i>j, (5,5))

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False]])

In [60]:
list[np.fromfunction(lambda i,j: i<j, (5,5))]

list[array([[False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])]

In [61]:
np.fromfunction(lambda i,j: i*j, (5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [62]:
range(5)

range(0, 5)

In [63]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
range(2,11)

range(2, 11)

In [66]:
list(range(2,11))

[2, 3, 4, 5, 6, 7, 8, 9, 10]

In [69]:
range(0.3,5.6)
#this gives error because the range function is not allowing to floating point numbers so we can use 
#""iter function"" in the numpy library

TypeError: 'float' object cannot be interpreted as an integer

In [74]:
#iter function

In [84]:
list(i*i for i in range(0,6))

[0, 1, 4, 9, 16, 25]

In [85]:
np.fromiter(list(i*i for i in range(0,6)),float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [86]:
iterable=list(i*i for i in range(0,6))

In [87]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [88]:
np.fromstring("22 34 23 45 223 ",sep=" ")

array([ 22.,  34.,  23.,  45., 223.])

In [89]:
np.fromstring("2,4, 23 45 ,23 ",sep=",")

C:\Users\chand\AppData\Local\Temp\ipykernel_24304\3275093684.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("2,4, 23 45 ,23 ",sep=",")


array([ 2.,  4., 23.])

In [90]:
np.fromstring("2,4,5,6,7,8,3,5,7,43,3 ",sep=",")

array([ 2.,  4.,  5.,  6.,  7.,  8.,  3.,  5.,  7., 43.,  3.])

In [91]:
arr

array([233,   2,   3,   4,   5,   6])

In [92]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [93]:
arr.ndim

1

In [94]:
arr1.ndim

2

In [95]:
arr.shape

(6,)

In [96]:
arr1.shape

(2, 3)

In [97]:
arr1.dtype

dtype('int32')

In [99]:
arr.dtype

dtype('int32')