In [1]:
#1...
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))       # Will print the type of list_
print(type(array_list))  # Will print the type of array_list
print(list_.dtype)       # This will raise an AttributeError because Python lists do not have a 'dtype' attribute
print(array_list.dtype)  # Will print the data type of elements inside array_list


<class 'list'>
<class 'numpy.ndarray'>


AttributeError: 'list' object has no attribute 'dtype'

In [2]:
#2...
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for item in list_:
    print(type(item))

# Print data type of each element in array_list
for item in array_list:
    print(type(item))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
#3...
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for item in list_:
    print(type(item))  # Will print <class 'str'>

# Print data type of each element in array_list
for item in array_list:
    print(type(item))  # Will print <class 'numpy.int32'> or <class 'numpy.int64'> depending on the system



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [4]:
#4...
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find and print the shape of num_array
print(num_array.shape)  # (i) shape

# Find and print the size of num_array
print(num_array.size)   # (ii) size


(2, 3)
6


In [5]:
#5...
import numpy as np

# Create a 3x3 matrix containing zeros
zero_array = np.zeros((3, 3))

print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
